##############################################################
# Makefile.rules for dbf
#
# History:
# $Log$
# Revision 1.8  2004-04-25 16:02:51  rollinhand
# removed iodbf.* from dependings
#
# Revision 1.7  2003/12/16 19:15:08  rollinhand
# Adopted to Version 0.9pre
#
# Revision 1.6  2003/11/20 12:56:39  rollin_hand
# *** empty log message ***
#
# Revision 1.5  2003/11/19 06:59:57  steinm
# - CHANGELOG is now ChangeLog
#
# Revision 1.4  2003/11/13 11:16:26  rollin_hand
# changed  to 'gcc' instead of full path
#
##############################################################

# Compiler flags
CC = gcc
CFLAGS = -Wall

# Settings
LOG = make.log
DIRS = src
BIN = dbf
VERSION = 0.9pre
PREFIX = /usr/local

# Compiler settings - do not change
# erased dbfversion.o
OBJ = an_string.o codepages.o congraph.o csv.o dbf.o endian.o sql.o statistic.o
HDR = $(OBJ:%.o=%.h)
SRC = $(OBJ:%.o=%.c)
DOC = BUGS ChangeLog README CREDITS MANIFEST INSTALL FAQ


# Layout
YELLOW = \033[1;33m
NORMAL = \033[m
GREEN = \033[1;32m
RED = \033[1;31m

.c.o:
	$(CC) $(CFLAGS) -c $<
